### ISSUE TITLE
After install and Open it pops the docs folder

### ISSUE THREAD

**Issue by tgiffin** [openalloc/FINporter#6]
1. installed the app from the app store on my MacBook pro
2. I opened the app
3. It opened a finder window for the documents folder.
4. I can't get to the app even after I close the window - it just keeps opening the finder window for the documents folder

**Comment by reedes** [comment]
I assume this is for the FlowAllocator app.

By design it opens a file selector window to select an existing document file. (It's a document-centric app.)

There should also be a "New Document" button. Are you not seeing that?

<img width="799" alt="Screen Shot 2021-10-29 at 1 22 44 PM" src="https://user-images.githubusercontent.com/6090039/139490829-c9110299-362c-4be3-8e01-ceee7f26200a.png">

**Comment by tgiffin** [comment]
yes -- I didn't have any document to upload -- I wanted to see the UI before I did that.  I deleted the app.  It also was sucking CPU and draining battery on the laptop.  I looked through the docs and screenshots I could find-- it didn't help me based on what I saw with my allocateSmartly portfolios.  thank you for your response.

**Comment by reedes** [comment]
Admittedly the docs are still pretty sparse, but the plan is to improve them over time.

I've been investigating the CPU issue. So far I've been unable to reproduce what you're seeing, but I've been making internal changes that could address it. It'll be in 1.5 which should be up next week.

Thanks for giving the app a try. Please check back in a few weeks or months to see if things have improved.
